window.CSJOBS_JOBS = [
  {
    "Posted Date": "2026-08-27",
    "Application Deadline": "2026-10-12",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Research statement; Three letters of recommendation",
    "University": "Reed College",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Computer Systems",
    "Lat/Long": "45.4801, -122.6295",
    "City": "Portland, Oregon",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32528",
    "Input Tokens": "961",
    "Output Tokens": "190"
  },
  {
    "Posted Date": "2026-08-27",
    "Application Deadline": "2026-11-06",
    "Application Materials": "Cover letter; Curriculum vitae; Personal statement covering research, teaching, and service; Three confidential professional references",
    "University": "Texas A&M University",
    "Department": "Department of Statistics and Data Science",
    "Position Title": "Assistant Professor",
    "Lat/Long": "30.6187, -96.3365",
    "City": "College Station, Texas",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32525",
    "Input Tokens": "756",
    "Output Tokens": "180"
  },
  {
    "Posted Date": "2026-08-26",
    "Application Deadline": "2026-09-30",
    "Application Materials": "CV; Cover letter; Research statement; Teaching statement",
    "University": "University of Bath",
    "Department": "Department of Computer Science",
    "Position Title": "Lecturer / Senior Lecturer / Reader in Cyber Security",
    "Lat/Long": "51.3781, -2.3274",
    "City": "Bath, Somerset, United Kingdom",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32517",
    "Input Tokens": "1818",
    "Output Tokens": "266"
  },
  {
    "Posted Date": "2026-08-23",
    "Application Deadline": "2026-11-20",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Service and/or diversity statement; Contact information for 3–4 references",
    "University": "Rice University",
    "Department": "Rice Advanced Materials Institute (RAMI); home department to be determined",
    "Position Title": "Assistant Professor of Advanced Materials",
    "Lat/Long": "29.7174, -95.4018",
    "City": "Houston, Texas",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32498",
    "Input Tokens": "1894",
    "Output Tokens": "207"
  },
  {
    "Posted Date": "2026-08-21",
    "Application Deadline": "2026-10-16",
    "Application Materials": "Application materials as specified in the NMSU application portal",
    "University": "New Mexico State University",
    "Department": "Institute for Applied Practice in AI and Machine Learning",
    "Position Title": "Assistant Professor of Artificial Intelligence Education",
    "Lat/Long": "32.2824, -106.7489",
    "City": "Las Cruces, New Mexico",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32496",
    "Input Tokens": "1126",
    "Output Tokens": "209"
  },
  {
    "Posted Date": "2026-08-21",
    "Application Deadline": "2026-10-05",
    "Application Materials": "Curriculum vitae; Letter of interest; Teaching statement; Research statement; Diversity statement; Contact information for three references",
    "University": "University of Puget Sound",
    "Department": "Department of Biology",
    "Position Title": "Assistant Professor of Biology",
    "Lat/Long": "47.2640, -122.4820",
    "City": "Tacoma, Washington",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32495",
    "Input Tokens": "2186",
    "Output Tokens": "163"
  },
  {
    "Posted Date": "2026-08-21",
    "Application Deadline": "December 11, 2026",
    "Application Materials": "Brief letter of interest; Research statement describing accomplishments, goals, and potential collaborations; Teaching statement; Current curriculum vitae; Contact information for three references",
    "University": "Boston University",
    "Department": "Department of Biomedical Engineering",
    "Position Title": "Tenure-Track Assistant Professor in Brain Health, Neuroscience, and Computational Modeling/Data Science",
    "Lat/Long": "42.3505, -71.1054",
    "City": "Boston, Massachusetts",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32490",
    "Input Tokens": "1390",
    "Output Tokens": "187"
  },
  {
    "Posted Date": "2026-08-20",
    "Application Deadline": "2026-09-30",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Writing sample; Three letters of recommendation",
    "University": "Columbia University",
    "Department": "School of International and Public Affairs",
    "Position Title": "Assistant Professor of AI and Data Science for Public Policy",
    "Lat/Long": "40.8075, -73.9626",
    "City": "New York, New York",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32487",
    "Input Tokens": "971",
    "Output Tokens": "205"
  },
  {
    "Posted Date": "2026-08-18",
    "Application Deadline": "2026-09-15",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Equity, diversity, inclusion, and Indigeneity statement",
    "University": "University of British Columbia",
    "Department": "Faculty of Applied Science, School of Engineering, Civil Engineering Program",
    "Position Title": "Assistant or Associate Professor in Civil Engineering",
    "Lat/Long": "49.9401, -119.3972",
    "City": "Kelowna, British Columbia",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32478",
    "Input Tokens": "2035",
    "Output Tokens": "198"
  },
  {
    "Posted Date": "2026-08-18",
    "Application Deadline": "2026-09-15",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Equity, diversity, inclusion, and Indigeneity statement",
    "University": "University of British Columbia",
    "Department": "Faculty of Applied Science, School of Engineering, Electrical and Computer Engineering",
    "Position Title": "Assistant or Associate Professor of Teaching in Electrical and Computer Engineering",
    "Lat/Long": "49.9394, -119.3948",
    "City": "Kelowna, British Columbia",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32477",
    "Input Tokens": "1875",
    "Output Tokens": "252"
  },
  {
    "Posted Date": "2026-08-18",
    "Application Deadline": "2026-09-15",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Equity, diversity, inclusion, and Indigeneity statement",
    "University": "University of British Columbia",
    "Department": "Faculty of Applied Science, School of Engineering, Civil Engineering Program",
    "Position Title": "Assistant or Associate Professor of Teaching in Civil Engineering",
    "Lat/Long": "49.9394, -119.3970",
    "City": "Kelowna, British Columbia",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32476",
    "Input Tokens": "1840",
    "Output Tokens": "227"
  },
  {
    "Posted Date": "2026-08-13",
    "Application Deadline": "2026-10-12",
    "Application Materials": "Cover letter; Curriculum vitae; Statement responding to the Hillsdale College Mission Statement; Teaching statement; Research statement; Graduate transcript; At least three letters of recommendation, including at least one addressing teaching ability",
    "University": "Hillsdale College",
    "Department": "Department of Mathematics and Computer Science",
    "Position Title": "Tenure-Track Assistant or Associate Professor of Computer Science",
    "Lat/Long": "41.9260, -84.6305",
    "City": "Hillsdale, Michigan",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32459",
    "Input Tokens": "870",
    "Output Tokens": "241"
  },
  {
    "Posted Date": "2026-08-12",
    "Application Deadline": "2026-11-01",
    "Application Materials": "Cover letter; Curriculum vitae with complete publication list; Research statement; Teaching statement; Up to 2 representative publications or preprints; Contact information for at least 3 recommenders",
    "University": "Stanford University",
    "Department": "Department of Statistics",
    "Position Title": "Tenure-track Assistant Professor of Statistics",
    "Lat/Long": "37.4275, -122.1697",
    "City": "Stanford, California",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32447",
    "Input Tokens": "946",
    "Output Tokens": "174"
  },
  {
    "Posted Date": "2026-08-11",
    "Application Deadline": "2026-09-15",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Equity, diversity, inclusion, and Indigeneity statement",
    "University": "University of British Columbia",
    "Department": "School of Engineering, Faculty of Applied Science",
    "Position Title": "Assistant or Associate Professor of Teaching in Mechanical and Manufacturing Engineering",
    "Lat/Long": "49.9394, -119.3960",
    "City": "Kelowna, British Columbia",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32441",
    "Input Tokens": "1880",
    "Output Tokens": "249"
  },
  {
    "Posted Date": "2026-08-10",
    "Application Deadline": "2026-10-02",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement (maximum 2 pages); Teaching statement (maximum 1 page); Equity, diversity, and inclusion statement (maximum 1 page); Contact information for four referees",
    "University": "University of Victoria",
    "Department": "Department of Mechanical Engineering",
    "Position Title": "Assistant Professor, Mechatronics and Robotics",
    "Lat/Long": "48.4634, -123.3117",
    "City": "Victoria, British Columbia, Canada",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32433",
    "Input Tokens": "2174",
    "Output Tokens": "191"
  },
  {
    "Posted Date": "2026-08-12",
    "Application Deadline": "October 15, 2026",
    "Application Materials": "Curriculum vitae; Job market paper; Three letters of recommendation",
    "University": "Stanford University",
    "Department": "Graduate School of Business, Operations, Information and Technology Area",
    "Position Title": "Assistant Professor of Operations, Information and Technology",
    "Lat/Long": "37.4275, -122.1697",
    "City": "Stanford, California",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32413",
    "Input Tokens": "997",
    "Output Tokens": "189"
  },
  {
    "Posted Date": "2026-08-01",
    "Application Deadline": "2026-10-20",
    "Application Materials": "Cover letter; Curriculum vitae; Current and proposed research statement (up to 5 pages); Teaching philosophy statement (about 1 page); Mentoring statement (about 1 page); At least three letters of recommendation for Assistant Professor applicants",
    "University": "Massachusetts Institute of Technology",
    "Department": "Department of Biology",
    "Position Title": "Assistant Professor or Tenured Associate/Full Professor of Biology",
    "Lat/Long": "42.3601, -71.0942",
    "City": "Cambridge, Massachusetts",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32330",
    "Input Tokens": "1228",
    "Output Tokens": "199"
  },
  {
    "Posted Date": "2026-07-14",
    "Application Deadline": "2026-10-01",
    "Application Materials": "Cover letter; Curriculum vitae; Three-page research statement; One-page mentoring philosophy statement; Three letters of recommendation",
    "University": "Duke University",
    "Department": "Discovery AI Initiative and Departments of Biochemistry, Cell Biology, Integrative Immunobiology, Neurobiology, and Pharmacology & Cancer Biology",
    "Position Title": "Tenure-Track Assistant Professor in AI/ML for Biology",
    "Lat/Long": "36.0014, -78.9382",
    "City": "Durham, North Carolina",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32313",
    "Input Tokens": "1238",
    "Output Tokens": "228"
  },
  {
    "Posted Date": "2026-07-13",
    "Application Deadline": "2026-11-09",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching dossier, including teaching statement, sample syllabi and course materials, and teaching evaluations; Three signed reference letters submitted directly by referees",
    "University": "University of Toronto",
    "Department": "Department of Statistical Sciences, Faculty of Arts and Science",
    "Position Title": "Assistant Professor of Statistical Learning Theory",
    "Lat/Long": "43.6629, -79.3957",
    "City": "Toronto, Ontario",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32307",
    "Input Tokens": "1391",
    "Output Tokens": "203"
  },
  {
    "Posted Date": "2026-07-01",
    "Application Deadline": "2026-09-30",
    "Application Materials": "Cover letter; Curriculum vitae; Publication list; Research statement; Teaching statement; Leadership statement; Descriptions of three most important achievements; Certificate of highest degree",
    "University": "ETH Zurich",
    "Department": "Department of Computer Science and Department of Mathematics",
    "Position Title": "Professors of Artificial Intelligence and Mathematical and Computational Foundations",
    "Lat/Long": "47.3769, 8.5476",
    "City": "Heilbronn, Baden-Württemberg, Germany",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32272",
    "Input Tokens": "922",
    "Output Tokens": "305"
  },
  {
    "Posted Date": "2026-07-01",
    "Application Deadline": "2026-09-30",
    "Application Materials": "Cover letter addressed to the President of ETH Zurich; Curriculum vitae; Publication list; Research statement; Teaching statement; Leadership statement; Descriptions of three most important achievements; Certificate of highest degree",
    "University": "ETH Zurich",
    "Department": "Department of Computer Science (D-INFK)",
    "Position Title": "Professor of Generative AI in Visual Computing",
    "Lat/Long": "49.1427, 9.2109",
    "City": "Heilbronn, Baden-Württemberg, Germany",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32271",
    "Input Tokens": "968",
    "Output Tokens": "287"
  },
  {
    "Posted Date": "2026-07-01",
    "Application Deadline": "2026-10-04",
    "Application Materials": "Cover letter; Curriculum vitae; Graduate transcripts; Teaching philosophy statement; Scholarship/research statement; Statement on mentoring a diverse student body; Three or more reference letters, including at least one teaching evaluation",
    "University": "Pomona College",
    "Department": "Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "34.0972, -117.7136",
    "City": "Claremont, California",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32241",
    "Input Tokens": "1089",
    "Output Tokens": "289"
  },
  {
    "Posted Date": "2026-07-01",
    "Application Deadline": "2026-09-01",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Research statement; Diversity, equity, and inclusion/mentoring statement; Summary of teaching evaluations; Up to three publication or research samples; Three letters of recommendation",
    "University": "Pomona College",
    "Department": "Department of Linguistics and Cognitive Science",
    "Position Title": "Assistant Professor of Cognitive Science",
    "Lat/Long": "34.0972, -117.7117",
    "City": "Claremont, California",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32240",
    "Input Tokens": "1038",
    "Output Tokens": "244"
  },
  {
    "Posted Date": "2026-09-04",
    "Application Deadline": "2026-11-16",
    "Application Materials": "Cover letter; Curriculum vitae; List of publications; Research statement; Teaching statement; Three confidential recommendation letters (Assistant Professor) or contact information for three references (Associate Professor)",
    "University": "University of Chicago",
    "Department": "Department of Astronomy & Astrophysics",
    "Position Title": "Assistant/Associate Professor in Astronomy & Astrophysics",
    "Lat/Long": "41.7886, -87.5987",
    "City": "Chicago, Illinois",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32618",
    "Input Tokens": "1381",
    "Output Tokens": "216"
  },
  {
    "Posted Date": "2026-09-04",
    "Application Deadline": "2026-10-01",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement with evidence of teaching effectiveness; Diversity, equity, and inclusion statement; Research interest group fit and collaboration statement; Three representative reprints; Three recommendation letters",
    "University": "Rice University",
    "Department": "Department of Psychological Sciences",
    "Position Title": "Assistant Professor of Human-Centered AI in Health",
    "Lat/Long": "29.7174, -95.4018",
    "City": "Houston, Texas",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32614",
    "Input Tokens": "1456",
    "Output Tokens": "193"
  },
  {
    "Posted Date": "2026-09-01",
    "Application Deadline": "November 22, 2026",
    "Application Materials": "Letter of interest; Curriculum vitae; Up to three research papers; Three recommendation letters; Teaching record and evidence of teaching effectiveness; Optional supporting documents, such as curriculum development materials",
    "University": "Cornell University",
    "Department": "Cornell SC Johnson College of Business, Finance Area",
    "Position Title": "Assistant or Associate Professor of Finance",
    "Lat/Long": "42.4534, -76.4735",
    "City": "Ithaca, New York",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32569",
    "Input Tokens": "1834",
    "Output Tokens": "366"
  },
  {
    "Posted Date": "2026-08-31",
    "Application Deadline": "2026-10-16",
    "Application Materials": "Curriculum vitae; Letter of interest; Teaching statement; Research statement; Diversity statement; Contact information for three references",
    "University": "University of Puget Sound",
    "Department": "Math & Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "47.2646, -122.4829",
    "City": "Tacoma, Washington",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32563",
    "Input Tokens": "1771",
    "Output Tokens": "181"
  },
  {
    "Posted Date": "2026-09-04",
    "Application Deadline": "2026-10-31",
    "Application Materials": "Curriculum vitae; Cover letter; Research statement; Teaching statement; Reference letters",
    "University": "Boston University",
    "Department": "Faculty of Computing & Data Sciences",
    "Position Title": "Tenure-Track Assistant Professor of Public Interest AI",
    "Lat/Long": "42.3505, -71.1054",
    "City": "Boston, Massachusetts",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32562",
    "Input Tokens": "1166",
    "Output Tokens": "290"
  },
  {
    "Posted Date": "2026-09-04",
    "Application Deadline": "2026-12-01",
    "Application Materials": "Curriculum vitae; Research statement; Teaching and mentoring plan; Broader impact statement; Three representative reprints or preprints; Three recommendation letters",
    "University": "Massachusetts Institute of Technology",
    "Department": "Department of Brain and Cognitive Sciences",
    "Position Title": "Tenure-Track Assistant Professor in Brain and Cognitive Sciences",
    "Lat/Long": "42.3601, -71.0942",
    "City": "Cambridge, Massachusetts",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32511",
    "Input Tokens": "1042",
    "Output Tokens": "191"
  },
  {
    "Posted Date": "2026-08-20",
    "Application Deadline": "2026-10-01",
    "Application Materials": "See application website for required materials",
    "University": "Northwestern University",
    "Department": "Department of Statistics and Data Science",
    "Position Title": "Assistant Professor and Open-Rank Faculty",
    "Lat/Long": "42.0565, -87.6753",
    "City": "Evanston, Illinois",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2395",
    "Input Tokens": "703",
    "Output Tokens": "224"
  },
  {
    "Posted Date": "2026-07-31",
    "Application Deadline": "Not specified",
    "Application Materials": "Not specified in the listing; see the full job posting for required materials",
    "University": "University of Florida",
    "Department": "Department of Computer and Information Science and Engineering",
    "Position Title": "Assistant/Associate/Full Professor of AI Models, Systems and Applications",
    "Lat/Long": "30.3322, -81.6557",
    "City": "Jacksonville, Florida",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2376",
    "Input Tokens": "773",
    "Output Tokens": "279"
  },
  {
    "Posted Date": "2026-09-08",
    "Application Deadline": "2026-11-28",
    "Application Materials": "Online application materials; specific documents not specified",
    "University": "Stony Brook University",
    "Department": "Department of Biomedical Informatics",
    "Position Title": "Clinical Data Scientist, Assistant/Associate Professor (Tenure-Track)",
    "Lat/Long": "40.9149, -73.1234",
    "City": "Stony Brook, New York",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2413",
    "Input Tokens": "1632",
    "Output Tokens": "242"
  },
  {
    "Posted Date": "2026-09-03",
    "Application Deadline": "Not specified",
    "Application Materials": "See full job announcement and application procedures",
    "University": "Montana State University",
    "Department": "Gianforte School of Computing",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "45.6670, -111.0500",
    "City": "Bozeman, Montana",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2410",
    "Input Tokens": "684",
    "Output Tokens": "206"
  },
  {
    "Posted Date": "2026-09-03",
    "Application Deadline": "Not specified",
    "Application Materials": "Not specified in the listing; apply through the provided Interfolio links",
    "University": "Baylor University",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track and Tenured Faculty Positions in Artificial Intelligence and Cybersecurity",
    "Lat/Long": "31.5489, -97.1147",
    "City": "Waco, Texas",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2409",
    "Input Tokens": "606",
    "Output Tokens": "231"
  },
  {
    "Posted Date": "2026-09-02",
    "Application Deadline": "2026-09-30 (fullest consideration; review begins immediately and continues until filled)",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; References",
    "University": "The University of Alabama",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-track faculty, all ranks",
    "Lat/Long": "33.2098, -87.5692",
    "City": "Tuscaloosa, Alabama",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2407",
    "Input Tokens": "911",
    "Output Tokens": "320"
  },
  {
    "Posted Date": "2026-09-01",
    "Application Deadline": "2026-10-01",
    "Application Materials": "See application portal for required materials",
    "University": "Hamilton College",
    "Department": "Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "43.0481, -75.3785",
    "City": "Clinton, New York",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2406",
    "Input Tokens": "578",
    "Output Tokens": "219"
  },
  {
    "Posted Date": "2026-08-31",
    "Application Deadline": "Not specified",
    "Application Materials": "See application portal for required documents; materials are not specified in the listing",
    "University": "University of Massachusetts Lowell",
    "Department": "Miner School of Computer & Information Sciences",
    "Position Title": "Open Rank Tenure-Track Faculty in Core AI",
    "Lat/Long": "42.6559, -71.3245",
    "City": "Lowell, Massachusetts",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2405",
    "Input Tokens": "716",
    "Output Tokens": "230"
  },
  {
    "Posted Date": "2026-08-27",
    "Application Deadline": "2026-10-05",
    "Application Materials": "Curriculum vitae; Cover letter; Teaching statement; Research statement; References",
    "University": "Davidson College",
    "Department": "Department of Mathematics and Computer Science",
    "Position Title": "Tenure-Track Assistant Professor of Computer Science",
    "Lat/Long": "35.4993, -80.8487",
    "City": "Davidson, North Carolina",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2403",
    "Input Tokens": "670",
    "Output Tokens": "210"
  },
  {
    "Posted Date": "2026-08-24",
    "Application Deadline": "Not specified",
    "Application Materials": "",
    "University": "Oklahoma State University",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-track Assistant Professor of Computer Science",
    "Lat/Long": "36.1156, -97.0584",
    "City": "Stillwater, Oklahoma",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2400",
    "Input Tokens": "663",
    "Output Tokens": "168"
  },
  {
    "Posted Date": "2026-08-21",
    "Application Deadline": "Not specified",
    "Application Materials": "",
    "University": "University of Bath",
    "Department": "Department of Computer Science",
    "Position Title": "Lecturer / Senior Lecturer / Reader in Cyber Security",
    "Lat/Long": "51.3781, -2.3274",
    "City": "Bath, England, United Kingdom",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2397",
    "Input Tokens": "566",
    "Output Tokens": "162"
  },
  {
    "Posted Date": "2026-08-21",
    "Application Deadline": "2026-10-16",
    "Application Materials": "Application submitted through the online portal; Curriculum vitae; Cover letter; Research statement; Teaching statement; References",
    "University": "New Mexico State University",
    "Department": "AI Institute",
    "Position Title": "Assistant Professor of Artificial Intelligence Education",
    "Lat/Long": "32.2828, -106.7486",
    "City": "Las Cruces, New Mexico",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2396",
    "Input Tokens": "979",
    "Output Tokens": "264"
  },
  {
    "Posted Date": "2026-08-20",
    "Application Deadline": "2026-10-12",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Research statement; Three letters of recommendation",
    "University": "Reed College",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor in Computer Systems",
    "Lat/Long": "45.4801, -122.6295",
    "City": "Portland, Oregon",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2394",
    "Input Tokens": "959",
    "Output Tokens": "162"
  },
  {
    "Posted Date": "2026-08-20",
    "Application Deadline": "2026-10-02",
    "Application Materials": "Cover letter; Curriculum vitae; Undergraduate and graduate transcripts; Teaching statement; Research statement; Contact information for three professional references",
    "University": "Grinnell College",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track Assistant Professor of Computer Science",
    "Lat/Long": "41.7469, -92.7218",
    "City": "Grinnell, Iowa",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2393",
    "Input Tokens": "758",
    "Output Tokens": "204"
  },
  {
    "Posted Date": "2026-08-19",
    "Application Deadline": "2026-12-01",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Contact information for four references",
    "University": "Princeton University",
    "Department": "Princeton Quantum Initiative, Department of Computer Science, and Department of Electrical and Computer Engineering",
    "Position Title": "Assistant Professor in Quantum Information Theory and Quantum Computer Science",
    "Lat/Long": "40.3431, -74.6514",
    "City": "Princeton, New Jersey",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2392",
    "Input Tokens": "702",
    "Output Tokens": "240"
  },
  {
    "Posted Date": "2026-08-18",
    "Application Deadline": "Not specified",
    "Application Materials": "Application materials not specified; apply through the online application portal",
    "University": "St. Olaf College",
    "Department": "Department of Mathematics, Statistics, and Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "44.46, -93.18",
    "City": "Northfield, Minnesota",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2390",
    "Input Tokens": "616",
    "Output Tokens": "161"
  },
  {
    "Posted Date": "2026-08-18",
    "Application Deadline": "Not specified",
    "Application Materials": "",
    "University": "University of Iowa",
    "Department": "Department of Business Analytics, Tippie College of Business",
    "Position Title": "Tenure-Track Faculty in Business Analytics (Assistant, Associate, or Full Professor)",
    "Lat/Long": "41.6611, -91.5302",
    "City": "Iowa City, Iowa",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2389",
    "Input Tokens": "604",
    "Output Tokens": "162"
  },
  {
    "Posted Date": "2026-08-13",
    "Application Deadline": "2026-10-12",
    "Application Materials": "Cover letter; Curriculum vitae; Statement responding to the Hillsdale College Mission Statement; Teaching statement; Research statement; Graduate transcript; At least three letters of recommendation, including at least one addressing teaching ability",
    "University": "Hillsdale College",
    "Department": "Department of Mathematics and Computer Science",
    "Position Title": "Tenure-Track Assistant or Associate Professor of Computer Science",
    "Lat/Long": "41.9260, -84.6320",
    "City": "Hillsdale, Michigan",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2386",
    "Input Tokens": "857",
    "Output Tokens": "231"
  },
  {
    "Posted Date": "2026-08-12",
    "Application Deadline": "2026-10-15 9:00 PM Pacific Time",
    "Application Materials": "Curriculum vitae; Job market paper; Three letters of recommendation",
    "University": "Stanford University",
    "Department": "Operations, Information and Technology, Graduate School of Business",
    "Position Title": "Assistant Professor of Operations, Information and Technology",
    "Lat/Long": "37.4275, -122.1697",
    "City": "Stanford, California",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2385",
    "Input Tokens": "1002",
    "Output Tokens": "208"
  },
  {
    "Posted Date": "2026-08-10",
    "Application Deadline": "October 1, 2026",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Diversity, equity, and inclusion statement; Contact information for references",
    "University": "Bowdoin College",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track Assistant Professor of Computer Science",
    "Lat/Long": "43.9067, -69.9634",
    "City": "Brunswick, Maine",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2381",
    "Input Tokens": "749",
    "Output Tokens": "244"
  },
  {
    "Posted Date": "2026-07-30",
    "Application Deadline": "2026-10-11",
    "Application Materials": "Application materials as specified in the application portal; completed applications will be reviewed beginning October 11, 2026",
    "University": "California State Polytechnic University, Pomona (Cal Poly Pomona)",
    "Department": "Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "34.0561, -117.8228",
    "City": "Pomona, California",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2375",
    "Input Tokens": "688",
    "Output Tokens": "255"
  },
  {
    "Posted Date": "2026-07-28",
    "Application Deadline": "2026-10-01",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; Reference letters",
    "University": "Duke University",
    "Department": "Biochemistry; Cell Biology; Integrative Immunobiology; Neurobiology; Pharmacology & Cancer Biology",
    "Position Title": "Assistant Professor in AI/ML for Biology",
    "Lat/Long": "36.0014, -78.9382",
    "City": "Durham, North Carolina",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2373",
    "Input Tokens": "953",
    "Output Tokens": "250"
  },
  {
    "Posted Date": "2026-07-28",
    "Application Deadline": "Not specified",
    "Application Materials": "",
    "University": "Haverford College",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track Assistant Professor of Computer Science",
    "Lat/Long": "40.0132, -75.3060",
    "City": "Haverford, Pennsylvania",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2372",
    "Input Tokens": "636",
    "Output Tokens": "183"
  },
  {
    "Posted Date": "2026-09-03",
    "Application Deadline": "2026-11-01",
    "Application Materials": "Application materials submitted through the Harvard ARIeS portal; specific documents are not listed",
    "University": "Harvard University",
    "Department": "Department of Statistics, Faculty of Arts and Sciences",
    "Position Title": "Tenure-Track Professor in Statistics and AI",
    "Lat/Long": "42.3770, -71.1167",
    "City": "Cambridge, Massachusetts",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2411",
    "Input Tokens": "729",
    "Output Tokens": "298"
  },
  {
    "Posted Date": "2026-08-19",
    "Application Deadline": "Not specified",
    "Application Materials": "Cover letter; Curriculum vitae; Names and contact information for three references; Teaching statement; Research statement",
    "University": "University of Michigan-Flint",
    "Department": "College of Innovation & Technology",
    "Position Title": "Assistant Professor of Cybersecurity",
    "Lat/Long": "43.0195, -83.6875",
    "City": "Flint, Michigan",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2391",
    "Input Tokens": "675",
    "Output Tokens": "201"
  },
  {
    "Posted Date": "2026-08-11",
    "Application Deadline": "Not specified",
    "Application Materials": "",
    "University": "Northwestern University",
    "Department": "Industrial Engineering and Management Sciences (IEMS)",
    "Position Title": "Assistant Professor or Open-Rank Faculty in Industrial Engineering and Management Sciences",
    "Lat/Long": "42.0565, -87.6753",
    "City": "Evanston, Illinois",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2382",
    "Input Tokens": "558",
    "Output Tokens": "183"
  },
  {
    "Posted Date": "2026-08-12",
    "Application Deadline": "Not specified",
    "Application Materials": "Not specified in the provided listing",
    "University": "Harvey Mudd College",
    "Department": "Interdisciplinary Artificial Intelligence",
    "Position Title": "Assistant Professor or Open Rank in Artificial Intelligence",
    "Lat/Long": "34.1064, -117.7110",
    "City": "Claremont, California",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2384",
    "Input Tokens": "618",
    "Output Tokens": "323"
  },
  {
    "Posted Date": "2026-08-11",
    "Application Deadline": "September 30, 2026",
    "Application Materials": "See full application instructions at the linked application portal",
    "University": "Columbia University",
    "Department": "School of International and Public Affairs",
    "Position Title": "Assistant Professor of AI and Data Science for Public Policy",
    "Lat/Long": "40.8075, -73.9626",
    "City": "New York, New York",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2383",
    "Input Tokens": "581",
    "Output Tokens": "205"
  },
  {
    "Posted Date": "2026-08-07",
    "Application Deadline": "2026-09-20",
    "Application Materials": "Curriculum vitae; Research statement; Teaching statement; Diversity/equity statement; Names of references or recommendation letters; UMSI faculty mentor designation; Separate PPFP application",
    "University": "University of Michigan",
    "Department": "School of Information",
    "Position Title": "Assistant Professor of Privacy and Technology",
    "Lat/Long": "42.2780, -83.7382",
    "City": "Ann Arbor, Michigan",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2380",
    "Input Tokens": "996",
    "Output Tokens": "359"
  },
  {
    "Posted Date": "2026-08-04",
    "Application Deadline": "2026-10-01",
    "Application Materials": "See application portal for required application materials",
    "University": "Bates College",
    "Department": "Program in Africana and Program in Digital & Computational Studies",
    "Position Title": "Open-Rank Professor of Africana and Digital & Computational Studies",
    "Lat/Long": "44.1059, -70.2023",
    "City": "Lewiston, Maine",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2377",
    "Input Tokens": "602",
    "Output Tokens": "230"
  },
  {
    "Posted Date": "2026-07-27",
    "Application Deadline": "2026-09-15",
    "Application Materials": "Curriculum vitae; Cover letter; Research statement; Teaching statement; Recommendation letters",
    "University": "Northwestern University",
    "Department": "Management and Organizations, Kellogg School of Management",
    "Position Title": "Assistant Professor, Management and Organizations",
    "Lat/Long": "42.0565, -87.6753",
    "City": "Evanston, Illinois",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2370",
    "Input Tokens": "717",
    "Output Tokens": "290"
  },
  {
    "Posted Date": "2026-09-09",
    "Application Deadline": "2026-12-01",
    "Application Materials": "Curriculum vitae; Research statement; Teaching and mentoring plan; Broader impact statement; Three representative reprints or preprints; Three recommendation letters",
    "University": "Massachusetts Institute of Technology (MIT)",
    "Department": "Department of Brain and Cognitive Sciences; McGovern Institute for Brain Research",
    "Position Title": "Tenure-track Assistant Professor or higher in Neuroscience",
    "Lat/Long": "42.3601, -71.0942",
    "City": "Cambridge, Massachusetts",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32642",
    "Input Tokens": "1121",
    "Output Tokens": "184"
  },
  {
    "Posted Date": "2026-09-09",
    "Application Deadline": "2026-11-01",
    "Application Materials": "Research and teaching statement/letter; Curriculum vitae; Names of three referees for recommendation letters",
    "University": "Stanford University",
    "Department": "Department of Biomedical Data Science, Stanford University School of Medicine",
    "Position Title": "Open-Rank Professor of Biomedical Data Science",
    "Lat/Long": "37.4275, -122.1697",
    "City": "Stanford, California",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32656",
    "Input Tokens": "1595",
    "Output Tokens": "191"
  },
  {
    "Posted Date": "2026-09-09",
    "Application Deadline": "2026-11-28",
    "Application Materials": "Application materials not specified; submit all materials online",
    "University": "Stony Brook University",
    "Department": "Department of Biomedical Informatics",
    "Position Title": "Clinical Data Scientist, Assistant/Associate Professor",
    "Lat/Long": "40.9176, -73.1234",
    "City": "Stony Brook, New York",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32655",
    "Input Tokens": "1647",
    "Output Tokens": "268"
  },
  {
    "Posted Date": "2026-09-10",
    "Application Deadline": "2026-10-15",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Evidence of teaching effectiveness; Educational Leadership Vision Statement; Three letters of reference; Diversity statement",
    "University": "University of British Columbia",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Teaching in Systems (Tenure Track)",
    "Lat/Long": "49.2606, -123.2460",
    "City": "Vancouver, British Columbia",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32649",
    "Input Tokens": "2399",
    "Output Tokens": "219"
  },
  {
    "Posted Date": "2026-09-11",
    "Application Deadline": "Review begins immediately; open until filled",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; References; Official transcripts upon selection as a finalist",
    "University": "University of Houston",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Human-Centered Robotics and Assistive Systems",
    "Lat/Long": "29.7199, -95.3422",
    "City": "Houston, Texas",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2420",
    "Input Tokens": "1173",
    "Output Tokens": "260"
  },
  {
    "Posted Date": "2026-09-11",
    "Application Deadline": "Review begins immediately; open until filled",
    "Application Materials": "Curriculum vitae; Research statement; Teaching statement; Cover letter; Official transcripts upon selection",
    "University": "University of Houston",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Quantum Information Science",
    "Lat/Long": "29.7199, -95.3422",
    "City": "Houston, Texas",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2419",
    "Input Tokens": "1201",
    "Output Tokens": "282"
  },
  {
    "Posted Date": "2026-09-10",
    "Application Deadline": "Not specified in the listing",
    "Application Materials": "Application materials specified on the EECS employment opportunities page; apply via Interfolio",
    "University": "University of Tennessee, Knoxville",
    "Department": "Min H. Kao Department of Electrical Engineering and Computer Science",
    "Position Title": "Tenure-Track Assistant Professor positions in Electrical Engineering, Computer Engineering, and Computer Science; HPC Professorship",
    "Lat/Long": "35.9544, -83.9295",
    "City": "Knoxville, Tennessee",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2414",
    "Input Tokens": "830",
    "Output Tokens": "295"
  },
  {
    "Posted Date": "2026-09-11",
    "Application Deadline": "2026-10-15",
    "Application Materials": "Curriculum vitae; Cover letter; Teaching statement; Equity, diversity, and inclusion statement; Names and contact information for references",
    "University": "University of British Columbia",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Teaching in Systems",
    "Lat/Long": "49.2606, -123.2460",
    "City": "Vancouver, British Columbia, Canada",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2421",
    "Input Tokens": "615",
    "Output Tokens": "243"
  },
  {
    "Posted Date": "2026-09-14",
    "Application Deadline": "Not specified",
    "Application Materials": "Application submitted through the Missouri S&T careers portal",
    "University": "Missouri University of Science & Technology",
    "Department": "Computer Science",
    "Position Title": "Assistant or Associate Professor (tenure-track/tenured)",
    "Lat/Long": "37.9547, -91.7735",
    "City": "Rolla, Missouri",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2422",
    "Input Tokens": "850",
    "Output Tokens": "212"
  },
  {
    "Posted Date": "2026-09-15",
    "Application Deadline": "December 1, 2026 (priority deadline; applications accepted until filled)",
    "Application Materials": "Cover letter; Curriculum vitae; Research strategy (maximum 3 pages); Teaching and mentoring philosophy statement (1 page); Up to 3 significant publications with brief significance statements; Three letters of recommendation; Required misconduct or policy-violation disclosures",
    "University": "Duke University",
    "Department": "Department of Neurobiology, Duke University School of Medicine",
    "Position Title": "Tenure-Track Assistant Professor in Computational or Theoretical Neuroscience",
    "Lat/Long": "36.0014, -78.9382",
    "City": "Durham, North Carolina",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32697",
    "Input Tokens": "1204",
    "Output Tokens": "280"
  },
  {
    "Posted Date": "2026-09-15",
    "Application Deadline": "2026-12-15",
    "Application Materials": "Curriculum vitae; Teaching philosophy statement; Research philosophy statement; Three confidential letters of recommendation",
    "University": "Florida State University",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track Assistant Professor and Open Rank Professor",
    "Lat/Long": "30.4383, -84.2807",
    "City": "Tallahassee, Florida",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2425",
    "Input Tokens": "899",
    "Output Tokens": "212"
  },
  {
    "Posted Date": "2026-09-14",
    "Application Deadline": "2027-01-15",
    "Application Materials": "Curriculum vitae; Cover letter; Teaching statement; Research statement; References",
    "University": "Southern Illinois University Edwardsville",
    "Department": "Department of Computer Science",
    "Position Title": "Tenure-Track Assistant, Associate, or Full Professor in Computer Science/Cybersecurity Engineering",
    "Lat/Long": "38.7937, -89.9973",
    "City": "Edwardsville, Illinois",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2423",
    "Input Tokens": "616",
    "Output Tokens": "226"
  },
  {
    "Posted Date": "2026-09-16",
    "Application Deadline": "2026-10-15",
    "Application Materials": "Cover letter; Curriculum vitae; Teaching statement; Research statement",
    "University": "Bates College",
    "Department": "Program in Digital and Computational Studies",
    "Position Title": "Open-Rank Tenure-Line Professor of Digital and Computational Studies",
    "Lat/Long": "44.1059, -70.2023",
    "City": "Lewiston, Maine",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32722",
    "Input Tokens": "1416",
    "Output Tokens": "186"
  },
  {
    "Posted Date": "September 15, 2026",
    "Application Deadline": "November 18, 2026 (first review; open until filled)",
    "Application Materials": "Cover letter; Curriculum vitae; Publication list; Research statement; Teaching statement; Three confidential recommendation letters",
    "University": "University of Oklahoma",
    "Department": "Homer L. Dodge Department of Physics and Astronomy",
    "Position Title": "Tenure-Track Assistant Professor of Theoretical AMO Physics",
    "Lat/Long": "35.2058, -97.4457",
    "City": "Norman, Oklahoma",
    "Listing Link": "https://academicjobsonline.org/ajo/jobs/32714",
    "Input Tokens": "850",
    "Output Tokens": "213"
  },
  {
    "Posted Date": "2026-09-15",
    "Application Deadline": "2026-11-02",
    "Application Materials": "Cover letter; Curriculum vitae; Research statement; Teaching statement; References",
    "University": "University of California, Berkeley",
    "Department": "School of Information",
    "Position Title": "Assistant Professor of Human-Computer Interaction",
    "Lat/Long": "37.8719, -122.2585",
    "City": "Berkeley, California",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2427",
    "Input Tokens": "731",
    "Output Tokens": "225"
  },
  {
    "Posted Date": "2026-09-16",
    "Application Deadline": "October 15, 2026",
    "Application Materials": "Not specified in the listing",
    "University": "Franklin College",
    "Department": "Computing",
    "Position Title": "Tenure-Track Assistant Professor of Computing",
    "Lat/Long": "39.4806, -86.0547",
    "City": "Franklin, Indiana",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2430",
    "Input Tokens": "594",
    "Output Tokens": "236"
  },
  {
    "Posted Date": "2026-09-16",
    "Application Deadline": "2026-10-12",
    "Application Materials": "Cover letter; Curriculum vitae with publication list; Research statement; Teaching and mentoring statement; At least three confidential recommendation letters",
    "University": "University of Chicago",
    "Department": "Department of Computer Science",
    "Position Title": "Assistant Professor of Computer Science",
    "Lat/Long": "41.7897, -87.5997",
    "City": "Chicago, Illinois",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2429",
    "Input Tokens": "1126",
    "Output Tokens": "161"
  },
  {
    "Posted Date": "2026-09-16",
    "Application Deadline": "2026-10-15",
    "Application Materials": "Curriculum vitae; Cover letter; Teaching statement; Research statement; Contact information for references",
    "University": "Bates College",
    "Department": "Program in Digital and Computational Studies",
    "Position Title": "Open-Rank Tenure-Line Professor of Computer Science",
    "Lat/Long": "44.1057, -70.2036",
    "City": "Lewiston, Maine",
    "Listing Link": "https://careercenter.cra.org/jobs?job_id=2428",
    "Input Tokens": "634",
    "Output Tokens": "227"
  }
];
